use_frameworks!

platform :ios, '10.0'

target 'CommonExtension_Example' do
  pod 'CommonExtension', :path => '../'

  target 'CommonExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
